import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashLayout({ children }) {
  return (
       <div>
         <nav className="border-[1px] border-black">
          <ul className="flex justify-around">
           <li>
            <Link href="/faq">FAQ</Link>
           </li>
           <li>
            <Link href="/about">About</Link>
           </li>
         
          </ul>
        </nav>
        {children}
       </div>
  );
}
